spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
